### ISSUE TITLE
use acronyms

### ISSUE THREAD

**Issue by Wjxfi** [arturkowalczyk300/android-cryptocurrency-prices#22]
search not only as _monero_ but also as _xmr_. Search not only as _bitcoin_, but also as _btc_. 
and further

**Comment by arturkowalczyk300** [comment]
Thanks for idea!
Sounds useful, it will be added in the next release, stay tuned.

**Comment by arturkowalczyk300** [comment]
I have just added this feature. It's implemented in version v0.9.2: https://github.com/arturkowalczyk300/android-cryptocurrency-prices/releases/tag/v0.9.2
